// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMKfWBjB6GpnvMnFC-7UR7JEPiK9Tbck',
    appId: '1:885979881445:web:2f7d906e8795741c2d190c',
    messagingSenderId: '885979881445',
    projectId: 'laundriin-a1cfb',
    authDomain: 'laundriin-a1cfb.firebaseapp.com',
    storageBucket: 'laundriin-a1cfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeykO6MCVEn4_TB5WG_nZbCviqNxATm8',
    appId: '1:885979881445:android:1fc58fdc0c44f9ef2d190c',
    messagingSenderId: '885979881445',
    projectId: 'laundriin-a1cfb',
    storageBucket: 'laundriin-a1cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBziQioqAETcyiHuAwmEIYzqGGbcpI4yXU',
    appId: '1:885979881445:ios:6f38de86b169cdc52d190c',
    messagingSenderId: '885979881445',
    projectId: 'laundriin-a1cfb',
    storageBucket: 'laundriin-a1cfb.firebasestorage.app',
    iosBundleId: 'com.example.laundriinCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBziQioqAETcyiHuAwmEIYzqGGbcpI4yXU',
    appId: '1:885979881445:ios:6f38de86b169cdc52d190c',
    messagingSenderId: '885979881445',
    projectId: 'laundriin-a1cfb',
    storageBucket: 'laundriin-a1cfb.firebasestorage.app',
    iosBundleId: 'com.example.laundriinCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMKfWBjB6GpnvMnFC-7UR7JEPiK9Tbck',
    appId: '1:885979881445:web:49ea08bc9175df4a2d190c',
    messagingSenderId: '885979881445',
    projectId: 'laundriin-a1cfb',
    authDomain: 'laundriin-a1cfb.firebaseapp.com',
    storageBucket: 'laundriin-a1cfb.firebasestorage.app',
  );
}
